name: "portcullis"
description: Run all Portcullis steps in one go
keywords:
  - rnaseq
  - genome
  - splice
  - junction
tools:
  - "portcullis":
      description: "Portcullis is a tool that filters out invalid splice junctions from
        RNA-seq alignment data. It accepts BAM files from various RNA-seq mappers, analyzes
        splice  junctions, and  removes likely false positives, outputting filtered
        results in multiple formats for downstream analysis."
      homepage: "https://portcullis.readthedocs.io/en/latest/index.html"
      documentation: "https://portcullis.readthedocs.io/en/latest/using.html"
      doi: "10.1101/217620"
      license: ["GPL-3.0"]
      identifier: biotools:portcullis
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing information about the sample
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: Input bam file
  - - bed:
        type: file
        description: Input reference annotation of junctions in BED format
  - - fasta:
        type: file
        description: Input genome reference fasta file
output:
  - log:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.log"
      - "*.log":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.log"
  - bed:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.bed"
      - ${meta.id}/3-filt/*.bed:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.bed"
  - tab:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.tab"
      - ${meta.id}/3-filt/*.tab:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.tab"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "daniel.mapleson@earlham.ac.uk"
  - "luca.venturini@earlham.ac.uk"
  - "david.swarbreck@earlham.ac.uk"
maintainer:
  - "@blancoheredia"
